spring:
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: mongo-consumer-group
      auto-offset-reset: earliest
  data:
    mongodb:
      uri: mongodb://localhost:27017/randomdb
    redis:
      host: localhost
      port: 6379
logging:
  level:
    org:
      apache:
        kafka: ERROR
server:
  port: 3232
